"""
Derive a Page Access Token from a user token.

WHY THIS EXISTS
===============
Meta's Explorer hands out a USER token. Posting to a Page requires a PAGE
token. The Page token is obtained by calling /me/accounts and taking the
`access_token` of the matching Page.

Every earlier attempt failed on this distinction. Three Page tokens were
generated by hand, each bound to a different Page, and none carried
`pages_manage_posts`. A user token with Page access returns a derived Page
token whose scopes come from what the USER was granted, so it must be
derived rather than re-typed.

Also resolves the Page ID instead of trusting the value hardcoded in the seed
data, which pointed at a Page that does not exist.
"""

from __future__ import annotations

import json
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass

GRAPH = "https://graph.facebook.com/v19.0"


@dataclass
class DerivedPage:
    page_id: str
    name: str
    page_token: str

    def to_json(self) -> dict:
        return {
            "page_id": self.page_id,
            "name": self.name,
            "token_suffix": self.page_token[-8:],
        }


def _get(url: str, token: str, timeout: int = 30) -> dict:
    sep = "&" if "?" in url else "?"
    req = urllib.request.Request(
        f"{url}{sep}access_token={urllib.parse.quote(token)}",
        headers={"Accept": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.loads(r.read().decode("utf-8"))


def list_pages(user_token: str) -> list[DerivedPage]:
    """Every Page this user token can act on, with its Page token."""
    data = _get(f"{GRAPH}/me/accounts?fields=id,name,access_token", user_token)
    return [
        DerivedPage(
            page_id=p["id"],
            name=(p.get("name") or "").strip(),
            page_token=p["access_token"],
        )
        for p in data.get("data", [])
        if p.get("access_token")
    ]


def token_scopes(token: str) -> list[str]:
    """Scopes on a token, via /debug_token.

    Uses the token to authenticate itself, which /debug_token allows for
    tokens issued to the same app.
    """
    try:
        sep = "&" if "?" in f"{GRAPH}/debug_token" else ""
        url = (
            f"{GRAPH}/debug_token?input_token="
            f"{urllib.parse.quote(token)}&access_token="
            f"{urllib.parse.quote(token)}"
        )
        with urllib.request.urlopen(url, timeout=30) as r:
            return json.loads(r.read().decode("utf-8")).get("data", {}).get(
                "scopes", []
            )
    except (urllib.error.URLError, ValueError, KeyError):
        return []


CAN_POST = "pages_manage_posts"
CAN_READ = "pages_read_engagement"
CAN_MESSAGE = "pages_messaging"


def find_page(user_token: str, page_id: str = "", name_hint: str = "") -> DerivedPage | None:
    """Locate the intended Page.

    Prefers an explicit id; otherwise matches on a name hint, case and
    whitespace insensitive, because Facebook returns inconsistent spacing on
    Page names ("Shruhi collections" vs "Shruhi Collections").
    """
    pages = list_pages(user_token)
    if not pages:
        return None

    if page_id:
        for p in pages:
            if p.page_id == page_id:
                return p
        return None

    if name_hint:
        want = "".join(name_hint.lower().split())
        for p in pages:
            if "".join(p.name.lower().split()) == want:
                return p
        for p in pages:
            if want in "".join(p.name.lower().split()):
                return p

    return pages[0] if len(pages) == 1 else None


def capability_report(page_token: str) -> dict:
    """What this token can actually do, checked rather than assumed."""
    scopes = token_scopes(page_token)
    return {
        "scopes": scopes,
        "can_read_comments": CAN_READ in scopes,
        "can_send_dm": CAN_MESSAGE in scopes,
        "can_post": CAN_POST in scopes,
        "can_hide_comments": CAN_POST in scopes,
        "note": (
            "A Page token cannot be granted more than the user token behind "
            "it allows. If can_post is false, regenerate the USER token with "
            "the publish-content permission, then re-derive here."
        ),
    } if scopes else {
        "scopes": [],
        "can_read_comments": False,
        "can_send_dm": False,
        "can_post": False,
        "can_hide_comments": False,
        "note": "Could not read the token's scopes.",
    }
