"""Extract the brand hydration into a shared script both pages load."""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DASH = ROOT / "dashboard.html"

text = DASH.read_text(encoding="utf-8")

start = text.find("// Merchant brand hydration.")

if start == -1:
    raise SystemExit("could not find the hydration comment in dashboard.html")

# Brace-match the hydrateBrand function rather than guessing where the
# block ends. The first pass searched for a sentinel that appeared BEFORE
# the block, so it matched nothing.
fn = text.find("async function hydrateBrand", start)
if fn == -1:
    raise SystemExit("could not find hydrateBrand")

depth = 0
i = text.find("{", fn)
opened = i
while i < len(text):
    if text[i] == "{":
        depth += 1
    elif text[i] == "}":
        depth -= 1
        if depth == 0:
            break
    i += 1
end = i + 1

# Strip the leading indentation so it reads as a standalone file.
block = "\n".join(
    ln[2:] if ln.startswith("  ") else ln for ln in text[start:end].splitlines()
)
shared = block

shared_js = (
    "/**\n"
    " * Client brand hydration. GENERATED from dashboard.html by\n"
    " * scripts/extract_brand_js.py — edit the dashboard and re-run.\n"
    " *\n"
    " * Replaces marker tokens with the signed-in merchant's contact\n"
    " * details from /api/v1/client/{id}/brand. A missing value renders as\n"
    " * an em-dash rather than as another merchant's number.\n"
    " */\n"
    + shared
    + "\n\nif (typeof window !== 'undefined') window.hydrateBrand = hydrateBrand;\n"
)

(ROOT / "brand.js").write_text(shared_js, encoding="utf-8")
print(f"  wrote brand.js ({len(shared_js):,} bytes)")

# Replace the inline block in dashboard.html with a script tag.
replacement = (
    "// Merchant brand hydration lives in /brand.js so the pitch page can\n"
    "    // use it too. Generated by scripts/extract_brand_js.py.\n"
)
text2 = text[:start] + replacement + text[end:]
DASH.write_text(text2, encoding="utf-8")
print("  dashboard.html now loads /brand.js")

# Add the script tag to both pages.
for rel, anchor in (
    ("dashboard.html", "// Merchant brand hydration lives in /brand.js"),
    ("field_pitch.html", "</body>"),
):
    p = ROOT / rel
    t = p.read_text(encoding="utf-8")
    if "brand.js" in t and "src=\"/brand.js\"" in t:
        print(f"  {rel}: script tag already present")
        continue
    if rel == "dashboard.html":
        t = t.replace(
            anchor,
            '  <script src="/brand.js"></script>\n  <script>\n' + anchor,
            1,
        )
    else:
        t = t.replace(
            "</body>", '  <script src="/brand.js"></script>\n</body>', 1
        )
    p.write_text(t, encoding="utf-8")
    print(f"  {rel}: script tag added")

# brand.js must be copied into dist by the build.
b = ROOT / "scripts" / "build.py"
src = b.read_text(encoding="utf-8")
if '"brand.js"' not in src:
    src = src.replace(
        'STATIC_FILES = ["CNAME", "robots.txt", "sitemap.xml"]',
        'STATIC_FILES = ["CNAME", "robots.txt", "sitemap.xml", "brand.js"]',
    )
    b.write_text(src, encoding="utf-8")
    print("  build.py now copies brand.js")
